export interface Theme {
  id: string;
  name: string;
  tier: "free" | "pro";
  preview: string; // Gradient/color for the theme picker card
  variables: Record<string, string>;
}

export const themes: Theme[] = [
  // Free themes
  {
    id: "default",
    name: "Clean White",
    tier: "free",
    preview: "linear-gradient(135deg, #ffffff, #f3f4f6)",
    variables: {
      "--bg": "#ffffff",
      "--bg-gradient": "none",
      "--card-bg": "#ffffff",
      "--card-border": "#e5e7eb",
      "--text-primary": "#111827",
      "--text-secondary": "#6b7280",
      "--text-muted": "#9ca3af",
      "--accent": "#3b82f6",
      "--accent-hover": "#2563eb",
      "--radius": "0.75rem",
      "--font": "'Inter', system-ui, sans-serif",
    },
  },
  {
    id: "minimal",
    name: "Minimal Gray",
    tier: "free",
    preview: "linear-gradient(135deg, #f9fafb, #e5e7eb)",
    variables: {
      "--bg": "#f9fafb",
      "--bg-gradient": "none",
      "--card-bg": "#ffffff",
      "--card-border": "#d1d5db",
      "--text-primary": "#1f2937",
      "--text-secondary": "#6b7280",
      "--text-muted": "#9ca3af",
      "--accent": "#4b5563",
      "--accent-hover": "#374151",
      "--radius": "0.5rem",
      "--font": "'Inter', system-ui, sans-serif",
    },
  },
  {
    id: "dark",
    name: "Dark Mode",
    tier: "free",
    preview: "linear-gradient(135deg, #111827, #1f2937)",
    variables: {
      "--bg": "#111827",
      "--bg-gradient": "none",
      "--card-bg": "#1f2937",
      "--card-border": "#374151",
      "--text-primary": "#f9fafb",
      "--text-secondary": "#d1d5db",
      "--text-muted": "#6b7280",
      "--accent": "#60a5fa",
      "--accent-hover": "#3b82f6",
      "--radius": "0.75rem",
      "--font": "'Inter', system-ui, sans-serif",
    },
  },
  // Pro themes
  {
    id: "gradient-sunset",
    name: "Sunset",
    tier: "pro",
    preview: "linear-gradient(135deg, #f97316, #ec4899)",
    variables: {
      "--bg": "#1a1a2e",
      "--bg-gradient": "linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)",
      "--card-bg": "rgba(255,255,255,0.08)",
      "--card-border": "rgba(249,115,22,0.3)",
      "--text-primary": "#fef3c7",
      "--text-secondary": "#fdba74",
      "--text-muted": "#9a8478",
      "--accent": "#f97316",
      "--accent-hover": "#ea580c",
      "--radius": "1rem",
      "--font": "'Inter', system-ui, sans-serif",
    },
  },
  {
    id: "gradient-ocean",
    name: "Ocean",
    tier: "pro",
    preview: "linear-gradient(135deg, #06b6d4, #3b82f6)",
    variables: {
      "--bg": "#0c1222",
      "--bg-gradient": "linear-gradient(135deg, #0c1222 0%, #0a1628 50%, #0d1f3c 100%)",
      "--card-bg": "rgba(255,255,255,0.06)",
      "--card-border": "rgba(6,182,212,0.3)",
      "--text-primary": "#e0f2fe",
      "--text-secondary": "#7dd3fc",
      "--text-muted": "#4a7a8f",
      "--accent": "#06b6d4",
      "--accent-hover": "#0891b2",
      "--radius": "1rem",
      "--font": "'Inter', system-ui, sans-serif",
    },
  },
  {
    id: "neon",
    name: "Neon",
    tier: "pro",
    preview: "linear-gradient(135deg, #a855f7, #06b6d4)",
    variables: {
      "--bg": "#0a0a0a",
      "--bg-gradient": "none",
      "--card-bg": "#111111",
      "--card-border": "rgba(168,85,247,0.5)",
      "--text-primary": "#e9d5ff",
      "--text-secondary": "#c084fc",
      "--text-muted": "#7c5a9e",
      "--accent": "#a855f7",
      "--accent-hover": "#9333ea",
      "--radius": "0.5rem",
      "--font": "'Space Mono', monospace",
    },
  },
  {
    id: "glassmorphism",
    name: "Glass",
    tier: "pro",
    preview: "linear-gradient(135deg, rgba(255,255,255,0.4), rgba(200,200,255,0.2))",
    variables: {
      "--bg": "#667eea",
      "--bg-gradient": "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
      "--card-bg": "rgba(255,255,255,0.15)",
      "--card-border": "rgba(255,255,255,0.25)",
      "--text-primary": "#ffffff",
      "--text-secondary": "rgba(255,255,255,0.8)",
      "--text-muted": "rgba(255,255,255,0.5)",
      "--accent": "#ffffff",
      "--accent-hover": "rgba(255,255,255,0.9)",
      "--radius": "1rem",
      "--font": "'Inter', system-ui, sans-serif",
    },
  },
  {
    id: "brutalist",
    name: "Brutalist",
    tier: "pro",
    preview: "linear-gradient(135deg, #fef08a, #ffffff)",
    variables: {
      "--bg": "#fef9c3",
      "--bg-gradient": "none",
      "--card-bg": "#ffffff",
      "--card-border": "#000000",
      "--text-primary": "#000000",
      "--text-secondary": "#1f2937",
      "--text-muted": "#4b5563",
      "--accent": "#000000",
      "--accent-hover": "#1f2937",
      "--radius": "0",
      "--font": "'Courier New', monospace",
    },
  },
  {
    id: "retro",
    name: "Retro",
    tier: "pro",
    preview: "linear-gradient(135deg, #f59e0b, #92400e)",
    variables: {
      "--bg": "#fef3c7",
      "--bg-gradient": "none",
      "--card-bg": "#fffbeb",
      "--card-border": "#d97706",
      "--text-primary": "#78350f",
      "--text-secondary": "#92400e",
      "--text-muted": "#b45309",
      "--accent": "#d97706",
      "--accent-hover": "#b45309",
      "--radius": "0.375rem",
      "--font": "'Georgia', serif",
    },
  },
  {
    id: "pastel",
    name: "Pastel",
    tier: "pro",
    preview: "linear-gradient(135deg, #fbcfe8, #c7d2fe, #a7f3d0)",
    variables: {
      "--bg": "#fdf2f8",
      "--bg-gradient": "linear-gradient(135deg, #fdf2f8 0%, #ede9fe 50%, #ecfdf5 100%)",
      "--card-bg": "rgba(255,255,255,0.7)",
      "--card-border": "#e9d5ff",
      "--text-primary": "#581c87",
      "--text-secondary": "#7e22ce",
      "--text-muted": "#a78bfa",
      "--accent": "#c084fc",
      "--accent-hover": "#a855f7",
      "--radius": "1.5rem",
      "--font": "'Inter', system-ui, sans-serif",
    },
  },
  {
    id: "midnight",
    name: "Midnight",
    tier: "pro",
    preview: "linear-gradient(135deg, #1e1b4b, #312e81)",
    variables: {
      "--bg": "#1e1b4b",
      "--bg-gradient": "linear-gradient(180deg, #1e1b4b 0%, #0f172a 100%)",
      "--card-bg": "rgba(99,102,241,0.1)",
      "--card-border": "rgba(99,102,241,0.3)",
      "--text-primary": "#e0e7ff",
      "--text-secondary": "#a5b4fc",
      "--text-muted": "#6366f1",
      "--accent": "#818cf8",
      "--accent-hover": "#6366f1",
      "--radius": "0.75rem",
      "--font": "'Inter', system-ui, sans-serif",
    },
  },
  {
    id: "forest",
    name: "Forest",
    tier: "pro",
    preview: "linear-gradient(135deg, #14532d, #166534)",
    variables: {
      "--bg": "#052e16",
      "--bg-gradient": "linear-gradient(180deg, #052e16 0%, #0a1f12 100%)",
      "--card-bg": "rgba(34,197,94,0.08)",
      "--card-border": "rgba(34,197,94,0.25)",
      "--text-primary": "#dcfce7",
      "--text-secondary": "#86efac",
      "--text-muted": "#2d7a4a",
      "--accent": "#22c55e",
      "--accent-hover": "#16a34a",
      "--radius": "0.75rem",
      "--font": "'Inter', system-ui, sans-serif",
    },
  },
  {
    id: "monochrome",
    name: "Monochrome",
    tier: "pro",
    preview: "linear-gradient(135deg, #18181b, #3f3f46)",
    variables: {
      "--bg": "#18181b",
      "--bg-gradient": "none",
      "--card-bg": "#27272a",
      "--card-border": "#3f3f46",
      "--text-primary": "#fafafa",
      "--text-secondary": "#a1a1aa",
      "--text-muted": "#52525b",
      "--accent": "#fafafa",
      "--accent-hover": "#d4d4d8",
      "--radius": "0.5rem",
      "--font": "'Inter', system-ui, sans-serif",
    },
  },
];

export function getTheme(id: string): Theme {
  return themes.find((t) => t.id === id) ?? themes[0];
}

export function getThemesByTier(tier: "free" | "pro"): Theme[] {
  if (tier === "pro") return themes;
  return themes.filter((t) => t.tier === "free");
}
